variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"


image: "maven:3.6.3-jdk-8"

maven-job:
  except:
    - 'master'
  script:
    - 'mvn versions:set -DnewVersion=0.6-SNAPSHOT'
    - 'mvn versions:update-child-modules'
    - 'mvn -U -DgitVer=git-$CI_COMMIT_SHORT_SHA- clean deploy -s ci_settings.xml'
  artifacts:
    paths:
      - target/team-selector-*.jar
    expire_in: 1 days

maven-job2:
  only:
    - 'master'
  script:
    - 'mvn versions:set -DnewVersion=0.6'
    - 'mvn versions:update-child-modules'
    - 'mvn -U -DgitVer=git-$CI_COMMIT_SHORT_SHA- clean deploy -s ci_settings.xml'
  after_script:
    - 'apt-get update && apt-get install -y -qq lftp'
    - 'lftp -c "set ftp:ssl-allow no; open -u $APIDOCS_USER,$APIDOCS_PASS andrei1058.com; mirror -Rev target/apidocs ./$CI_PROJECT_TITLE  --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/"'
  artifacts:
    paths:
      - target/team-selector-*.jar